### ISSUE TITLE
[Suggestion] UUID support

### ISSUE THREAD

**Issue by NotMyFault** [Crazy-Crew/Crazy-Auctions#100]
**Describe the suggestion**
A clear and concise description of what the suggestion is about.

I'm looking for (optional) uuid support, rather than storing auctions under the player name.
If a player changes their name, they can no longer interact with items being listed, which is pretty inconvenient. Storing items with their uuid shouldn't cause any complications if a player changes their name.

**Comment by JHarris12345** [comment]
Whats going on here
