### ISSUE TITLE
[Suggestion] Polish language

### ISSUE THREAD

**Issue by Axer22** [Crazy-Crew/Crazy-Auctions#110]
Hello, I've made polish translations to this plugin, if you want, you can add it.
messages.yml
https://paste.gg/p/anonymous/4b072718ea874092ab1a94ff603fdd0f
config.yml
https://paste.gg/p/anonymous/18768ee0959c4e8ab6fca6cd9bb1e692

**Comment by YellowDuckyDuck** [comment]
Thanks!

**Comment by RyderBelserion** [comment]
Lang/Config file will be changing
