### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by iAverages** [Crazy-Crew/Crazy-Auctions#112]
**Describe the bug**

Spamming the "Refresh button" on /ah causes server lag.

**Versions (please complete the following information):**
 - Minecraft Server Version: [e.g. 1.8.8]
 - Plugin Version: [e.g. 1.2.12]

*Do **NOT** say Latest use `/version crazyauctions` in the console.
 - Minecraft Server Version: Paper version git-Paper-372 (MC: 1.15.2)
![image](https://dannn.net/FoySW.png)
 - Plugin Version: Latest - 1.2.15-RELEASE
![image](https://dannn.net/mBNlg.png)

**Pastebin any errors in console**
Link: N/A

**Issue**
Spamming the "Refresh button" on /ah causes server lag.
Recreating is simple, spam the refresh button using an auto clicker. TPS will drop severely low.

**Screenshots**
![image](https://dannn.net/BHeRa.png)
![image](https://dannn.net/0JMFH.png)

**Comment by RyderBelserion** [comment]
Added to the board.
