### ISSUE TITLE
[Bug Report] None of my players have permission to use /ca.

### ISSUE THREAD

**Issue by adamm17** [Crazy-Crew/Crazy-Auctions#115]
I have given a perm node to each group, yet anyone who is not OP cannot use any commands.

These are the perm nodes:

    - crazyauctions.access
    - crazyauctions.sell
    - crazyauctions.sell.#
    - crazyauctions.bid 
    - crazyauctions.bid.#

Each one is setup, yet they do not have access.

**Comment by H1DD3NxN1NJA** [comment]
Crazyauctions.sell.# means how many items do you want them to sell, replace the # with that number like crazyauctions.sell.5. Hope this helps

**Comment by Zabujca997** [comment]
I have the same permissions and no player can use it without op

**Comment by xMilGG** [comment]
@Zabujca997 jestem z Polski, rozwiązałeś problem?
