### ISSUE TITLE
[Bug Report] Over-generous inventory detection picks up other plugins

### ISSUE THREAD

**Issue by mbax** [Crazy-Crew/Crazy-Auctions#124]
**Describe the bug**
Auction inventory detection results in meddling with other plugin-created inventories, such as preventing interaction.

**Versions (please complete the following information):**
 - Minecraft Server Version: Any, confirmed via source code
 - Plugin Version: 1.2.15

**Pastebin any errors in console**
Link: https://rb.gy/gq3vae

**Issue**
Here's an example from the code
https://github.com/badbones69/Crazy-Auctions/blob/4de44321cf616650bde6d1005be39abd0ee85917/src/main/java/me/badbones69/crazyauctions/controllers/GUI.java#L483-L484)

If, for whatever reason, a user configures this plugin and another plugin to have similar titles such that one of the CrazyAuctions titles is even just a *part* of that other plugin's title, CrazyAuctions will cancel the event at a minimum and possibly (untested) would take further CrazyAuctions actions based on a player's interaction inside another plugin's inventory. 

My experience was a PlayerVaults user who couldn't move items in to or out of their vault because (as determined after much testing and plugin binary searching), CrazyAuctions was configured to use a simple word as one of the inventory titles and PlayerVaults was configured to have its vault names start with that same simple word.

I believe this could be fixed fairly simply by utilizing a custom InventoryHolder rather than putting in `null` as you currently do when creating inventories, and then testing for that holder. But I don't play too much with inventory adventures and this may require something else like closer monitoring of when the player's in an auction related inventory. 🙂

**Comment by RyderBelserion** [comment]
Added to project board.
