### ISSUE TITLE
[Bug Report] NPE when clicking in menu.

### ISSUE THREAD

**Issue by SirKillian** [Crazy-Crew/Crazy-Auctions#126]
**Describe the bug**
Occasional Error, cant always replicate.

**Versions (please complete the following information):**
 - Minecraft Server Version: Tuinity 1.16.4
 - Plugin Version: 1.2.15

*Do **NOT** say Latest use `/version crazyauctions` in the console.

**Pastebin any errors in console**
https://pastebin.com/LSmaQuXU

**Issue**
Clicking items in the /ah menu gives an error sometimes.

**Comment by RyderBelserion** [comment]
Added to project board.
