### ISSUE TITLE
[Bug Report] CRITICAL Duplicate

### ISSUE THREAD

**Issue by Redstylt** [Crazy-Crew/Crazy-Auctions#128]
**Describe the bug**
When an item is on sell you shift-click on item to drop in your inventory and you get it ! (Not good at all !!!!)
Then you close the CA and open again and the item is there...You can continue like this indefinitely

**Versions (please complete the following information):**
 - Minecraft Server Version: Paper latest 1.16.5
 - Plugin Version: CrazyAuctions[v1.2.15].jar #36

**Issue**
It's a huge duplicate glitch. Had to remove the plugin in emergency

**Comment by H1DD3NxN1NJA** [comment]
Hello, can you please send a video of this duplicate bug so we have a source to go back to to see how to preform it properly. Also make sure in the video that you are not an operator to show the full default player perspective of the bug in action

**Comment by RyderBelserion** [comment]
Added to project board.
