### ISSUE TITLE
[Bug Report] permission node is not working i got my permission node from the official github command and permissions

### ISSUE THREAD

**Issue by ariestortle** [Crazy-Crew/Crazy-Auctions#140]
**Describe the bug**

**Versions (please complete the following information):**
 - Minecraft Server Version: [e.g. 1.8.8]
 - Plugin Version: [e.g. 1.2.12]

*Do **NOT** say Latest use `/version crazyauctions` in the console.

**Pastebin any errors in console**
Link: https://pastebin.com/

**Issue**
Describe the issue you are having with the plugin.

**Screenshots**

**Comment by aptint** [comment]
Can you please fill out the information you commented above? Can't help you without more information.

**Comment by RyderBelserion** [comment]
Added to project board.
