### ISSUE TITLE
Can take items from gui bug 

### ISSUE THREAD

**Issue by CaoTrongThang** [Crazy-Crew/Crazy-Auctions#88]
First of all, sorry about my bad English ~~"

i can take the items from gui if i changing the name of the GUI to something like "chó, mèo, chuột", but its working with CrazyCrates ~~"

Im using CrazyAuctions version 1.2.11-RELEASE and my server is using PaperSpigot 1.13.2

![image](https://user-images.githubusercontent.com/51023235/69373321-1e5a7200-0cd6-11ea-8b93-d4895588ca10.png)

**Comment by WizWazWizard** [comment]
This means its not working on your server, its either the version of Crazy Auctions or your own server version

**Comment by RyderBelserion** [comment]
Added to project board.
